#!/bin/bash
# Git Authentication Setup Script

echo "=========================================="
echo "GitHub Authentication Setup"
echo "=========================================="
echo ""
echo "GitHub no longer accepts passwords for HTTPS authentication."
echo "You need to use a Personal Access Token (PAT) instead."
echo ""
echo "Steps to create a PAT:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Give it a name (e.g., 'STOPPS Project')"
echo "4. Select scopes: at minimum check 'repo'"
echo "5. Click 'Generate token'"
echo "6. COPY THE TOKEN IMMEDIATELY (you won't see it again!)"
echo ""
echo "After you have your token, you can:"
echo ""
echo "Option A: Use Git Credential Helper (Recommended)"
echo "  Run: git config --global credential.helper store"
echo "  Then on next push, use your GitHub username and the PAT as password"
echo ""
echo "Option B: Update remote URL with token"
echo "  Run: git remote set-url origin https://YOUR_TOKEN@github.com/Ihame-b/STOPPS.git"
echo "  (Replace YOUR_TOKEN with your actual PAT)"
echo ""
echo "Option C: Switch to SSH (More secure, but requires SSH key setup)"
echo "  Run: git remote set-url origin git@github.com:Ihame-b/STOPPS.git"
echo ""
read -p "Press Enter to continue..."
