# Generated by Django 4.2.27 on 2026-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_alter_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='CampanyName',
            field=models.CharField(choices=[('LINFOX', 'linfox'), ('KBS', 'kbs'), ('OTHERS', 'others')], default='Linfox', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('MOMO', 'momo'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
