# Generated by Django 4.2.27 on 2026-02-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='customers'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cargo'),
        ),
    ]
