# Generated by Django 4.2.27 on 2026-02-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0025_emailverificationtoken'),
    ]

    operations = [
        migrations.RunSQL(
            # Add unique constraint to email field in auth_user table
            sql="ALTER TABLE auth_user ADD CONSTRAINT auth_user_email_unique UNIQUE (email);",
            reverse_sql="ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_email_unique;",
        ),
    ]
