# Generated by Django 4.2.27 on 2026-02-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0026_make_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='ecomapp.linfoxuser', verbose_name='Created By'),
        ),
    ]
